import test from 'node:test';import assert from 'node:assert/strict';import {CARDS,fresh,start,encounter,play,endTurn,reward,upgrade,validSave,pressure} from '../dist/game.mjs';
test('30 unique cards and valid fresh/run saves',()=>{assert.equal(CARDS.length,30);assert.equal(new Set(CARDS.map(c=>c.id)).size,30);const s=fresh();assert.ok(validSave(s));start(s);assert.ok(validSave(s));assert.equal(s.run.deck.length,10)});
test('energy is enforced and composure absorbs pressure',()=>{const s=fresh();start(s);encounter(s,'fight');s.run.hand=['boundary','deploy'];s.run.energy=1;assert.equal(play(s,1),false);assert.equal(s.run.energy,1);assert.equal(play(s,0),true);const hp=s.run.hp;endTurn(s);assert.equal(s.run.hp,hp);assert.equal(s.run.block,0);assert.equal(s.run.energy,3);assert.equal(s.run.hand.length,5)});
test('victories draft cards and all three bosses lead to win',()=>{const s=fresh();start(s);for(let stage=0;stage<9;stage++){encounter(s,'fight');assert.equal(s.run.enemy.boss,stage%3===2);s.run.enemy.hp=1;s.run.hand=['pitch'];play(s,0);if(stage<8){assert.equal(s.run.phase,'reward');const id=s.run.rewards[0];const count=s.run.deck.length;reward(s,id);assert.equal(s.run.deck.length,count+1);assert.equal(s.run.phase,'map')}}assert.equal(s.run.phase,'won');assert.equal(s.meta.wins,1);assert.equal(s.meta.xp,123);const xp=s.meta.xp;endTurn(s);assert.equal(s.meta.xp,xp)});
test('loss awards experience once; upgrades persist into new run',()=>{const s=fresh();start(s);encounter(s,'fight');s.run.hp=1;endTurn(s);assert.equal(s.run.phase,'lost');assert.equal(s.meta.xp,8);endTurn(s);assert.equal(s.meta.xp,8);s.meta.xp=30;assert.ok(upgrade(s));start(s);assert.equal(s.run.maxHp,65);assert.equal(upgrade(s),false)});
test('rest and networking advance but cannot skip bosses',()=>{const s=fresh();start(s);s.run.hp=40;encounter(s,'rest');assert.equal(s.run.hp,52);encounter(s,'event');assert.equal(s.run.deck.length,11);assert.equal(s.run.hp,48);encounter(s,'rest');assert.equal(s.run.phase,'combat');assert.ok(s.run.enemy.boss)});
test('pressure rises every third turn and weakening lasts one turn',()=>{const s=fresh();start(s);encounter(s,'fight');s.run.turn=3;s.run.weak=3;assert.equal(pressure(s.run),s.run.enemy.attack+1);endTurn(s);assert.equal(s.run.weak,0)});
test('malformed imports cannot become game state',()=>{const s=fresh();start(s);s.run.stage=1.5;assert.equal(validSave(s),false);start(s);encounter(s,'fight');s.run.enemy.name='<script>';assert.equal(validSave(s),false)});
test('a combat save round-trips without losing the active hand',()=>{const s=fresh();start(s);encounter(s,'fight');const loaded=JSON.parse(JSON.stringify(s));assert.ok(validSave(loaded));assert.deepEqual(loaded.run.hand,s.run.hand);assert.deepEqual(loaded.run.draw,s.run.draw);assert.deepEqual(loaded.run.enemy,s.run.enemy)});
